In [2]:
#import dependencies and the web scraping code from scrape.py
from sqlalchemy import create_engine
import pymysql
import pandas as pd
import numpy as np 
import time
from datetime import datetime
import json

# from config import connection 

# def homes_comparison(scraped_homes):
    #create a connection to the sql database 
    

with open('scraped_homes.txt', 'r') as output_file:
    output = str(output_file.read())
    new_data = json.loads(output)
#     print(new_data)
    
# engine = create_engine("mysql://xq5039a54f2ukgye:pzghos28lbhgg711@otwsl2e23jrxcqvx.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/lmib79r99ct0zdgq", echo=False)
# conn = engine.connect()
# cur = conn.cursor()

try: 
    homesdf = pd.DataFrame(new_data)
#     print(homes)
except: 
    print("cant do it")
    #put the results of the function into a dataframe
#     homesdf = pd.DataFrame(scraped_homes)
    
homesdf['datetime'] = datetime.now()

print(homesdf)

# homesdf.to_csv('data.csv', index = False)

#RUN THE QUERY AND GET THE ADDRESS FROM THE SQL DATABASE AS A LIST THEN GRAB THE ADDRESS FORM THE SCRAPED DATA AS A LIST THEN 
#FIND THE INDEX OF THE LIST OF ADDRESS FROM THE PANDAS DATAFRAME FOR WHICH THERE ARE NO MATCHES IN SQL 
#TO ILOC THE ROWS THAT ARE NOT IN SQL         
    
# for house in homesdf.iterrows():
    
#     retrieved_data = pd.read_sql("SELECT address FROM lmib79r99ct0zdgq.homes WHERE address = {}".format(house['address']), engine)
#     print(retrieved_data)
    
#     if retrieved_data:
        

    #what happens when the same house is sold within 3 years? homes sold more than once. Compare datestamp and address if datestamp is one year old 
    #append the data anyways 

    #loop through the dataframe table and compare it to the web scrape info
    # for house in homesdf.iterrows():




    #loop thorugh each new df scrape and compare it against the sql database
    # for i, house in homesdf.iterrows():
        #read the sql database and take the address column to compare 
        # retrieved_data = pd.read_sql(f"SELECT address FROM lmib79r99ct0zdgq.homes WHERE address = '{house['address']}'", engine)
        #grab the address from the web scrape and  
        #compare if the address exists against the address column in the sql database
        # if retrieved_data.empty:
        #     homesdf.iloc[i].to_sql('lmib79r99ct0zdgq.homes', if_exists = 'append', schema= 'online', con=conn)

    # cur.execute(f"INSERT INTO lmib79r99ct0zdgq VALUES homesdf")
    

    # conn.commit()
    
# cur.close()

# conn.close()

                    address             agent     city days    neighborhood  \
0  21807 Forest Glade Drive      Jodi Manfred   Humble   24  forest shadows
1       4706 Broadmark Lane    Cellina Stokes   Humble   66  forest shadows
2       4602 Fieldwick Lane  Michael Thiltgen   Humble   80  forest shadows
3     21802 Pine Cone Drive    Katherine Ware   Humble   81  forest shadows
4      4503 Clairfield Lane       Rick Raymor   Humble  122  forest shadows
5                       NaN               NaN      NaN  NaN             NaN
6     15202 Claypool Street     Rosa Gonzalez  Houston  111  aldine estates
7                       NaN               NaN      NaN  NaN             NaN

                                            office   price state    zip  \
0                                       JLA Realty  171500    TX  77338
1                                    Crowne Realty  189900    TX  77338
2                   Greenbriar Real Estate Service  239900    TX  77338
3                             Irie Properties, LLC  259500    TX  77338
4                                 RE/MAX Universal     NaN    TX  77338
5                                              NaN  199000   NaN    NaN
6  REALM Real Estate Professionals - North Houston     NaN    TX  77032
7                                              NaN  650000   NaN    NaN

                    datetime
0 2019-07-08 20:25:59.309478
1 2019-07-08 20:25:59.309478
2 2019-07-08 20:25:59.309478
3 2019-07-08 20:25:59.309478
4 2019-07-08 20:25:59.309478
5 2019-07-08 20:25:59.309478
6 2019-07-08 20:25:59.309478
7 2019-07-08 20:25:59.309478